// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_merchant.hpp"

#include <config/core.hpp>

#include "../skill_impl.hpp"

#include "abrbattlewarior.hpp"
#include "abrdualcannon.hpp"
#include "abrinfinity.hpp"
#include "abrmothernet.hpp"
#include "aciddemonstration.hpp"
#include "acidifiedzonefire.hpp"
#include "acidifiedzoneground.hpp"
#include "acidifiedzonewater.hpp"
#include "acidifiedzonewind.hpp"
#include "acidterror.hpp"
#include "adrenalinerush.hpp"
#include "advancedadrenalinerush.hpp"
#include "advanceprotection.hpp"
#include "aidberserkpotion.hpp"
#include "aidcondensedpotion.hpp"
#include "aidpotion.hpp"
#include "alchemicalweapon.hpp"
#include "analyze.hpp"
#include "armcannon.hpp"
#include "attackmachine.hpp"
#include "axeboomerang.hpp"
#include "axestomp.hpp"
#include "axetornado.hpp"
#include "backsideslide.hpp"
#include "biochemicalhelm.hpp"
#include "bionicpharmacy.hpp"
#include "bomb.hpp"
#include "boostknuckle.hpp"
#include "callhomunculus.hpp"
#include "cartcannon.hpp"
#include "cartrevolution.hpp"
#include "carttermination.hpp"
#include "carttornado.hpp"
#include "changecart.hpp"
#include "changematerial.hpp"
#include "coldslower.hpp"
#include "crazyuproar.hpp"
#include "crazyweed.hpp"
#include "createbomb.hpp"
#include "creeper.hpp"
#include "decoratecart.hpp"
#include "demonicfire.hpp"
#include "dustexplosion.hpp"
#include "emergencycool.hpp"
#include "energycannonade.hpp"
#include "explosivepowder.hpp"
#include "fawmagicdecoy.hpp"
#include "fawremoval.hpp"
#include "fawsilversniper.hpp"
#include "fireexpansion.hpp"
#include "flamelauncher.hpp"
#include "frontsideslide.hpp"
#include "fullprotection.hpp"
#include "greed.hpp"
#include "hammerfall.hpp"
#include "hellsplant.hpp"
#include "helltree.hpp"
#include "howlingofmandragora.hpp"
#include "illusiondoping.hpp"
#include "infraredscan.hpp"
#include "itemappraisal.hpp"
#include "magmaeruption.hpp"
#include "magneticfield.hpp"
#include "mammonite.hpp"
#include "manufacturemachine.hpp"
#include "mayhemicthorns.hpp"
#include "mightysmash.hpp"

#include "mixcooking.hpp"
#include "mysterypowder.hpp"
#include "neutralbarrier.hpp"
#include "pilebunker.hpp"
#include "plantcultivation.hpp"
#include "powerfulswing.hpp"
#include "powerswing.hpp"
#include "powerthrust.hpp"
#include "preparepotion.hpp"
#include "repair.hpp"
#include "rushquake.hpp"
#include "rushstrike.hpp"
#include "selfdestruction.hpp"
#include "skill_vending.hpp"
#include "slingitem.hpp"
#include "sparkblaster.hpp"
#include "specialpharmacy.hpp"
#include "sporeexplosion.hpp"
#include "stealthfield.hpp"
#include "summonflora.hpp"
#include "summonmarinesphere.hpp"
#include "synthesizedshield.hpp"
#include "syntheticarmor.hpp"
#include "thewholeprotection.hpp"
#include "thorntrap.hpp"
#include "triplelaser.hpp"
#include "twilightalchemy1.hpp"
#include "twilightalchemy2.hpp"
#include "twilightalchemy3.hpp"
#include "upgradeweapon.hpp"
#include "vaporize.hpp"
#include "vulcanarm.hpp"
#include "wallofthorns.hpp"
#include "weaponperfection.hpp"
#include "weaponrepair.hpp"
#include "woodenfairy.hpp"
#include "woodenwarrior.hpp"

std::unique_ptr<const SkillImpl> SkillFactoryMerchant::create(const e_skill skill_id) const {
	switch (skill_id) {
		case AM_ACIDTERROR:
			return std::make_unique<SkillAcidTerror>();
		case AM_BERSERKPITCHER:
			return std::make_unique<SkillAidBerserkPotion>();
		case AM_CALLHOMUN:
			return std::make_unique<SkillCallHomunculus>();
		case AM_CANNIBALIZE:
			return std::make_unique<SkillSummonFlora>();
		case AM_CP_ARMOR:
			return std::make_unique<SkillSyntheticArmor>();
		case AM_CP_HELM:
			return std::make_unique<SkillBiochemicalHelm>();
		case AM_CP_SHIELD:
			return std::make_unique<SkillSynthesizedShield>();
		case AM_CP_WEAPON:
			return std::make_unique<SkillAlchemicalWeapon>();
		case AM_DEMONSTRATION:
			return std::make_unique<SkillBomb>();
		case AM_PHARMACY:
			return std::make_unique<SkillPreparePotion>();
		case AM_POTIONPITCHER:
			return std::make_unique<SkillAidPotion>();
		case AM_REST:
			return std::make_unique<SkillVaporize>();
		case AM_SPHEREMINE:
			return std::make_unique<SkillSummonMarineSphere>();
		case AM_TWILIGHT1:
			return std::make_unique<SkillTwilightAlchemy1>();
		case AM_TWILIGHT2:
			return std::make_unique<SkillTwilightAlchemy2>();
		case AM_TWILIGHT3:
			return std::make_unique<SkillTwilightAlchemy3>();
		case BO_ACIDIFIED_ZONE_FIRE:
			return std::make_unique<SkillAcidifiedZoneFire>();
		case BO_ACIDIFIED_ZONE_FIRE_ATK:
			return std::make_unique<SkillActifiedZoneFireAttack>();
		case BO_ACIDIFIED_ZONE_GROUND:
			return std::make_unique<SkillAcidifiedZoneGround>();
		case BO_ACIDIFIED_ZONE_GROUND_ATK:
			return std::make_unique<SkillActifiedZoneGroundAttack>();
		case BO_ACIDIFIED_ZONE_WATER:
			return std::make_unique<SkillAcidifiedZoneWater>();
		case BO_ACIDIFIED_ZONE_WATER_ATK:
			return std::make_unique<SkillActifiedZoneWaterAttack>();
		case BO_ACIDIFIED_ZONE_WIND:
			return std::make_unique<SkillAcidifiedZoneWind>();
		case BO_ACIDIFIED_ZONE_WIND_ATK:
			return std::make_unique<SkillActifiedZoneWindAttack>();
		case BO_ADVANCE_PROTECTION:
			return std::make_unique<SkillAdvanceProtection>();
		case BO_BIONIC_PHARMACY:
			return std::make_unique<SkillBionicPharmacy>();
		case BO_CREEPER:
			return std::make_unique<SkillCreeper>();
		case BO_DUST_EXPLOSION:
			return std::make_unique<SkillDustExplosion>();
		case BO_EXPLOSIVE_POWDER:
			return std::make_unique<SkillExplosivePowder>();
		case BO_HELLTREE:
			return std::make_unique<SkillHellTree>();
		case BO_MAYHEMIC_THORNS:
			return std::make_unique<SkillMayhemicThorns>();
		case BO_MYSTERY_POWDER:
			return std::make_unique<SkillMysteryPowder>();
		case BO_RESEARCHREPORT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case BO_THE_WHOLE_PROTECTION:
			return std::make_unique<SkillTheWholeProtection>();
		case BO_WOODENWARRIOR:
			return std::make_unique<SkillWoodenWarrior>();
		case BO_WOODEN_ATTACK:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case BO_WOODEN_FAIRY:
			return std::make_unique<SkillWoodenFairy>();
		case BO_WOODEN_THROWROCK:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case BS_ADRENALINE:
			return std::make_unique<SkillAdrenalineRush>();
		case BS_ADRENALINE2:
			return std::make_unique<SkillAdvancedAdrenalineRush>();
		case BS_GREED:
			return std::make_unique<SkillGreed>();
		case BS_HAMMERFALL:
			return std::make_unique<SkillHammerFall>();
		case BS_MAXIMIZE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case BS_OVERTHRUST:
			return std::make_unique<SkillPowerThrust>();
		case BS_REPAIRWEAPON:
			return std::make_unique<SkillWeaponRepair>();
		case BS_WEAPONPERFECT:
			return std::make_unique<SkillWeaponPerfection>();
		case CR_ACIDDEMONSTRATION:
			return std::make_unique<SkillAcidDemonstration>();
		case CR_CULTIVATION:
			return std::make_unique<SkillPlantCultivation>();
		case CR_FULLPROTECTION:
			return std::make_unique<SkillFullProtection>();
		case CR_SLIMPITCHER:
			return std::make_unique<SkillAidCondensedPotion>();
		case GN_BLOOD_SUCKER:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case GN_CARTBOOST:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case GN_CARTCANNON:
			return std::make_unique<SkillCartCannon>();
		case GN_CART_TORNADO:
			return std::make_unique<SkillCartTornado>();
		case GN_CHANGEMATERIAL:
			return std::make_unique<SkillChangeMaterial>();
		case GN_CRAZYWEED:
			return std::make_unique<SkillCrazyWeed>();
		case GN_CRAZYWEED_ATK:
			return std::make_unique<SkillCrazyWeedAttack>();
		case GN_DEMONIC_FIRE:
			return std::make_unique<SkillDemonicFire>();
		case GN_FIRE_EXPANSION:
			return std::make_unique<SkillFireExpansion>();
		case GN_FIRE_EXPANSION_ACID:
			return std::make_unique<SkillFireExpansionAcid>();
		case GN_HELLS_PLANT:
			return std::make_unique<SkillHellsPlant>();
		case GN_HELLS_PLANT_ATK:
			return std::make_unique<SkillHellsPlantAttack>();
		case GN_ILLUSIONDOPING:
			return std::make_unique<SkillIllusionDoping>();
		case GN_MAKEBOMB:
			return std::make_unique<SkillCreateBomb>();
		case GN_MANDRAGORA:
			return std::make_unique<SkillHowlingOfMandragora>();
		case GN_MIX_COOKING:
			return std::make_unique<SkillMixCooking>();
		case GN_SLINGITEM:
			return std::make_unique<SkillSlingItem>();
		case GN_SLINGITEM_RANGEMELEEATK:
			return std::make_unique<SkillSlingItemAttack>();
		case GN_SPORE_EXPLOSION:
			return std::make_unique<SkillSporeExplosion>();
		case GN_S_PHARMACY:
			return std::make_unique<SkillSpecialPharmacy>();
		case GN_THORNS_TRAP:
			return std::make_unique<SkillThornTrap>();
		case GN_WALLOFTHORN:
			return std::make_unique<SkillWallOfThorns>();
		case MC_CARTDECORATE:
			return std::make_unique<SkillDecorateCart>();
		case MC_CARTREVOLUTION:
			return std::make_unique<SkillCartRevolution>();
		case MC_CHANGECART:
			return std::make_unique<SkillChangeCart>();
		case MC_IDENTIFY:
			return std::make_unique<SkillItemAppraisal>();
		case MC_LOUD:
			return std::make_unique<SkillCrazyUproar>();
		case MC_MAMMONITE:
			return std::make_unique<SkillMammonite>();
		case MC_VENDING:
			return std::make_unique<SkillVending>();
		case MT_AXE_STOMP:
			return std::make_unique<SkillAxeStomp>();
		case MT_A_MACHINE:
			return std::make_unique<SkillAttackMachine>();
		case MT_D_MACHINE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case MT_ENERGY_CANNONADE:
			return std::make_unique<SkillEnergyCannonade>();
		case MT_MIGHTY_SMASH:
			return std::make_unique<SkillMightySmash>();
		case MT_M_MACHINE:
			return std::make_unique<SkillManufactureMachine>();
		case MT_POWERFUL_SWING:
			return std::make_unique<SkillPowerfulSwing>();
		case MT_RUSH_QUAKE:
			return std::make_unique<SkillRushQuake>();
		case MT_RUSH_STRIKE:
			return std::make_unique<SkillRushStrike>();
		case MT_SPARK_BLASTER:
			return std::make_unique<SkillSparkBlaster>();
		case MT_SUMMON_ABR_BATTLE_WARIOR:
			return std::make_unique<SkillAbrBattleWarrior>();
		case MT_SUMMON_ABR_DUAL_CANNON:
			return std::make_unique<SkillAbrDualCannon>();
		case MT_SUMMON_ABR_INFINITY:
			return std::make_unique<SkillAbrInfinity>();
		case MT_SUMMON_ABR_MOTHER_NET:
			return std::make_unique<SkillAbrMotherNet>();
		case MT_TRIPLE_LASER:
			return std::make_unique<SkillTripleLaser>();
		case NC_ACCELERATION:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NC_ANALYZE:
			return std::make_unique<SkillAnalyze>();
		case NC_ARMSCANNON:
			return std::make_unique<SkillArmCannon>();
		case NC_AXEBOOMERANG:
			return std::make_unique<SkillAxeBoomerang>();
		case NC_AXETORNADO:
			return std::make_unique<SkillAxeTornado>();
		case NC_B_SIDESLIDE:
			return std::make_unique<SkillBackSideSlide>();
		case NC_BOOSTKNUCKLE:
			return std::make_unique<SkillBoostKnuckle>();
		case NC_COLDSLOWER:
			return std::make_unique<SkillColdSlower>();
		case NC_DISJOINT:
			return std::make_unique<SkillFawRemoval>();
		case NC_EMERGENCYCOOL:
			return std::make_unique<SkillEmergencyCool>();
		case NC_FLAMELAUNCHER:
			return std::make_unique<SkillFlameLauncher>();
		case NC_F_SIDESLIDE:
			return std::make_unique<SkillFrontSideSlide>();
		case NC_HOVERING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NC_INFRAREDSCAN:
			return std::make_unique<SkillInfraredScan>();
		case NC_MAGICDECOY:
			return std::make_unique<SkillFawMagicDecoy>();
		case NC_MAGMA_ERUPTION:
			return std::make_unique<SkillMagmaEruption>();
		case NC_MAGMA_ERUPTION_DOTDAMAGE:
			return std::make_unique<SkillMagmaEruptionDotDamage>();
		case NC_MAGNETICFIELD:
			return std::make_unique<SkillMagneticField>();
		case NC_NEUTRALBARRIER:
			return std::make_unique<SkillNeutralBarrier>();
		case NC_PILEBUNKER:
			return std::make_unique<SkillPileBunker>();
		case NC_POWERSWING:
			return std::make_unique<SkillPowerSwing>();
		case NC_REPAIR:
			return std::make_unique<SkillRepair>();
		case NC_SELFDESTRUCTION:
			return std::make_unique<SkillSelfDestruction>();
		case NC_SHAPESHIFT:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case NC_SILVERSNIPER:
			return std::make_unique<SkillFawSilverSniper>();
		case NC_STEALTHFIELD:
			return std::make_unique<SkillStealthField>();
		case NC_VULCANARM:
			return std::make_unique<SkillVulcanArm>();
		case WS_CARTBOOST:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WS_CARTTERMINATION:
			return std::make_unique<SkillCartTermination>();
		case WS_MELTDOWN:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WS_OVERTHRUSTMAX:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case WS_WEAPONREFINE:
			return std::make_unique<SkillUpgradeWeapon>();

		default:
			return nullptr;
	}
}
