// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_homunculus.hpp"

#include "../skill_impl.hpp"

#include "homunculus_absolutezephyr.hpp"
#include "homunculus_avoid.hpp"
#include "homunculus_benedictionofchaos.hpp"
#include "homunculus_bioexplosion.hpp"
#include "homunculus_blastforge.hpp"
#include "homunculus_blazingandfurious.hpp"
#include "homunculus_caprice.hpp"
#include "homunculus_castling.hpp"
#include "homunculus_change.hpp"
#include "homunculus_continualbreakcombo.hpp"
#include "homunculus_defense.hpp"
#include "homunculus_erasercutter.hpp"
#include "homunculus_eternalquickcombo.hpp"
#include "homunculus_glanzenspies.hpp"
#include "homunculus_goldenetone.hpp"
#include "homunculus_graniticarmor.hpp"
#include "homunculus_healingtouch.hpp"
#include "homunculus_heiligepferd.hpp"
#include "homunculus_holypole.hpp"
#include "homunculus_lavaslide.hpp"
#include "homunculus_lightofregene.hpp"
#include "homunculus_magmaflow.hpp"
#include "homunculus_midnightfrenzy.hpp"
#include "homunculus_needleofparalyze.hpp"
#include "homunculus_needlestinger.hpp"
#include "homunculus_overedboost.hpp"
#include "homunculus_painkiller.hpp"
#include "homunculus_poisonmist.hpp"
#include "homunculus_pyroclastic.hpp"
#include "homunculus_silentbreeze.hpp"
#include "homunculus_silverveinrush.hpp"
#include "homunculus_sonicclaw.hpp"
#include "homunculus_steelhorn.hpp"
#include "homunculus_stonewall.hpp"
#include "homunculus_stylechange.hpp"
#include "homunculus_summonlegion.hpp"
#include "homunculus_tempering.hpp"
#include "homunculus_theonefighterrises.hpp"
#include "homunculus_tinderbreaker.hpp"
#include "homunculus_toxinofmandara.hpp"
#include "homunculus_twistercutter.hpp"
#include "homunculus_volcanicash.hpp"
#include "homunculus_xenoslasher.hpp"

std::unique_ptr<const SkillImpl> SkillFactoryHomunculus::create(const e_skill skill_id) const {
	switch (skill_id) {
		case HAMI_BLOODLUST:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case HAMI_CASTLE:
			return std::make_unique<SkillCastling>();
		case HAMI_DEFENCE:
			return std::make_unique<SkillDefense>();
		case HFLI_FLEET:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case HFLI_MOON:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case HFLI_SBR44:
			return std::make_unique<WeaponSkillImpl>(skill_id);
		case HFLI_SPEED:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case HLIF_AVOID:
			return std::make_unique<SkillAvoid>();
		case HLIF_CHANGE:
			return std::make_unique<SkillChange>();
		case HLIF_HEAL:
			return std::make_unique<SkillHealingTouch>();
		case HVAN_CAPRICE:
			return std::make_unique<SkillCaprice>();
		case HVAN_CHAOTIC:
			return std::make_unique<SkillBenedictionOfChaos>();
		case HVAN_EXPLOSION:
			return std::make_unique<SkillBioExplosion>();
		case MH_ABSOLUTE_ZEPHYR:
			return std::make_unique<SkillAbsoluteZephyr>();
		case MH_ANGRIFFS_MODUS:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case MH_BLAST_FORGE:
			return std::make_unique<SkillBlastForge>();
		case MH_BLAZING_AND_FURIOUS:
			return std::make_unique<SkillBlazingAndFurious>();
		case MH_CBC:
			return std::make_unique<SkillContinualBreakCombo>();
		case MH_EQC:
			return std::make_unique<SkillEternalQuickCombo>();
		case MH_ERASER_CUTTER:
			return std::make_unique<SkillEraserCutter>();
		case MH_GLANZEN_SPIES:
			return std::make_unique<SkillGlanzenSpies>();
		case MH_GOLDENE_FERSE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case MH_GOLDENE_TONE:
			return std::make_unique<SkillGoldeneTone>();
		case MH_GRANITIC_ARMOR:
			return std::make_unique<SkillGraniticArmor>();
		case MH_HEILIGE_PFERD:
			return std::make_unique<SkillHeiligePferd>();
		case MH_HEILIGE_STANGE:
			return std::make_unique<SkillHolyPole>();
		case MH_LAVA_SLIDE:
			return std::make_unique<SkillLavaSlide>();
		case MH_LIGHT_OF_REGENE:
			return std::make_unique<SkillLightOfRegene>();
		case MH_MAGMA_FLOW:
			return std::make_unique<SkillMagmaFlow>();
		case MH_MIDNIGHT_FRENZY:
			return std::make_unique<SkillMidnightFrenzy>();
		case MH_NEEDLE_OF_PARALYZE:
			return std::make_unique<SkillNeedleOfParalyze>();
		case MH_NEEDLE_STINGER:
			return std::make_unique<SkillNeedleStinger>();
		case MH_OVERED_BOOST:
			return std::make_unique<SkillOveredBoost>();
		case MH_PAIN_KILLER:
			return std::make_unique<SkillPainKiller>();
		case MH_POISON_MIST:
			return std::make_unique<SkillPoisonMist>();
		case MH_PYROCLASTIC:
			return std::make_unique<SkillPyroclastic>();
		case MH_SILENT_BREEZE:
			return std::make_unique<SkillSilentBreeze>();
		case MH_SILVERVEIN_RUSH:
			return std::make_unique<SkillSilverVeinRush>();
		case MH_SONIC_CRAW:
			return std::make_unique<SkillSonicClaw>();
		case MH_STAHL_HORN:
			return std::make_unique<SkillSteelHorn>();
		case MH_STEINWAND:
			return std::make_unique<SkillStoneWall>();
		case MH_STYLE_CHANGE:
			return std::make_unique<SkillStyleChange>();
		case MH_SUMMON_LEGION:
			return std::make_unique<SkillSummonLegion>();
		case MH_TEMPERING:
			return std::make_unique<SkillTempering>();
		case MH_THE_ONE_FIGHTER_RISES:
			return std::make_unique<SkillTheOneFighterRises>();
		case MH_TINDER_BREAKER:
			return std::make_unique<SkillTinderBreaker>();
		case MH_TOXIN_OF_MANDARA:
			return std::make_unique<SkillToxinOfMandara>();
		case MH_TWISTER_CUTTER:
			return std::make_unique<SkillTwisterCutter>();
		case MH_VOLCANIC_ASH:
			return std::make_unique<SkillVolcanicAsh>();
		case MH_XENO_SLASHER:
			return std::make_unique<SkillXenoSlasher>();

		default:
			return nullptr;
	}
}
