set(MAP_SOURCES
	"achievement.cpp"
	"atcommand.cpp"
	"battle.cpp"
	"battleground.cpp"
	"buyingstore.cpp"
	"cashshop.cpp"
	"channel.cpp"
	"chat.cpp"
	"chrif.cpp"
	"clan.cpp"
	"clif.cpp"
	"date.cpp"
	"duel.cpp"
	"elemental.cpp"
	"guild.cpp"
	"homunculus.cpp"
	"instance.cpp"
	"intif.cpp"
	"itemdb.cpp"
	"log.cpp"
	"mail.cpp"
	"map.cpp"
	"mapreg.cpp"
	"mercenary.cpp"
	"mob.cpp"
	"navi.cpp"
	"npc.cpp"
	"npc_chat.cpp"
	"party.cpp"
	"path.cpp"
	"pc.cpp"
	"pc_groups.cpp"
	"pet.cpp"
	"quest.cpp"
	"script.cpp"
	"searchstore.cpp"
	"skill.cpp"
	"status.cpp"
	"storage.cpp"
	"trade.cpp"
	"unit.cpp"
	"vending.cpp"

	"skills/skill_factory.cpp"
	"skills/skill_impl.cpp"
	"skills/weapon_skill_impl.cpp"
	"skills/status_skill_impl.cpp"

	"skills/acolyte/adoramus.cpp"
	"skills/acolyte/ancilla.cpp"
	"skills/acolyte/angelus.cpp"
	"skills/acolyte/arbitrium.cpp"
	"skills/acolyte/aspersio.cpp"
	"skills/acolyte/blazingflameblast.cpp"
	"skills/acolyte/blessing.cpp"
	"skills/acolyte/bssacramenti.cpp"
	"skills/acolyte/cantocandidus.cpp"
	"skills/acolyte/clearance.cpp"
	"skills/acolyte/coluceoheal.cpp"
	"skills/acolyte/competentia.cpp"
	"skills/acolyte/convenio.cpp"
	"skills/acolyte/crementia.cpp"
	"skills/acolyte/crucis.cpp"
	"skills/acolyte/cure.cpp"
	"skills/acolyte/decagi.cpp"
	"skills/acolyte/dilectioheal.cpp"
	"skills/acolyte/divinusflos.cpp"
	"skills/acolyte/duplelight.cpp"
	"skills/acolyte/effligo.cpp"
	"skills/acolyte/epiclesis.cpp"
	"skills/acolyte/explosionblaster.cpp"
	"skills/acolyte/firstbrand.cpp"
	"skills/acolyte/framen.cpp"
	"skills/acolyte/gloria.cpp"
	"skills/acolyte/heal.cpp"
	"skills/acolyte/highnessheal.cpp"
	"skills/acolyte/holylight.cpp"
	"skills/acolyte/holywater.cpp"
	"skills/acolyte/impositiomanus.cpp"
	"skills/acolyte/incagi.cpp"
	"skills/acolyte/judex.cpp"
	"skills/acolyte/kyrieeleison.cpp"
	"skills/acolyte/laudaagnus.cpp"
	"skills/acolyte/laudaramus.cpp"
	"skills/acolyte/lexdivina.cpp"
	"skills/acolyte/magnificat.cpp"
	"skills/acolyte/magnusexorcismus.cpp"
	"skills/acolyte/massiveflameblaster.cpp"
	"skills/acolyte/medialevotum.cpp"
	"skills/acolyte/oleumsanctum.cpp"
	"skills/acolyte/oratio.cpp"
	"skills/acolyte/petitio.cpp"
	"skills/acolyte/pneuma.cpp"
	"skills/acolyte/pneumaticusprocella.cpp"
	"skills/acolyte/praefatio.cpp"
	"skills/acolyte/renovatio.cpp"
	"skills/acolyte/reparatio.cpp"
	"skills/acolyte/ruwach.cpp"
	"skills/acolyte/sanctuary.cpp"
	"skills/acolyte/secondfaith.cpp"
	"skills/acolyte/secondflame.cpp"
	"skills/acolyte/secondjudgement.cpp"
	"skills/acolyte/silentium.cpp"
	"skills/acolyte/skill_factory_acolyte.cpp"
	"skills/acolyte/statusrecovery.cpp"
	"skills/acolyte/suffragium.cpp"
	"skills/acolyte/thirdconsecration.cpp"
	"skills/acolyte/thirdflamebomb.cpp"
	"skills/acolyte/thirdpunish.cpp"
	"skills/acolyte/turnundead.cpp"
	"skills/acolyte/vituperatum.cpp"
	"skills/archer/aimedbolt.cpp"
	"skills/archer/anklesnare.cpp"
	"skills/archer/arrowshower.cpp"
	"skills/archer/arrowstorm.cpp"
	"skills/archer/beaststrafing.cpp"
	"skills/archer/blastmine.cpp"
	"skills/archer/blitzbeat.cpp"
	"skills/archer/camouflage.cpp"
	"skills/archer/chargearrow.cpp"
	"skills/archer/claymoretrap.cpp"
	"skills/archer/clusterbomb.cpp"
	"skills/archer/cobalttrap.cpp"
	"skills/archer/concentration.cpp"
	"skills/archer/crescivebolt.cpp"
	"skills/archer/deepblindtrap.cpp"
	"skills/archer/detect.cpp"
	"skills/archer/detonator.cpp"
	"skills/archer/doublestrafe.cpp"
	"skills/archer/electricshocker.cpp"
	"skills/archer/falconassault.cpp"
	"skills/archer/fearbreeze.cpp"
	"skills/archer/firingtrap.cpp"
	"skills/archer/flametrap.cpp"
	"skills/archer/flasher.cpp"
	"skills/archer/focusedarrowstrike.cpp"
	"skills/archer/freezingtrap.cpp"
	"skills/archer/galestorm.cpp"
	"skills/archer/hawkboomerang.cpp"
	"skills/archer/hawkmastery.cpp"
	"skills/archer/hawkrush.cpp"
	"skills/archer/iceboundtrap.cpp"
	"skills/archer/landmine.cpp"
	"skills/archer/magentatrap.cpp"
	"skills/archer/maizetrap.cpp"
	"skills/archer/makingarrow.cpp"
	"skills/archer/phantasmicarrow.cpp"
	"skills/archer/removetrap.cpp"
	"skills/archer/sandman.cpp"
	"skills/archer/sensitivekeen.cpp"
	"skills/archer/shockwavetrap.cpp"
	"skills/archer/skidtrap.cpp"
	"skills/archer/skill_factory_archer.cpp"
	"skills/archer/solidtrap.cpp"
	"skills/archer/springtrap.cpp"
	"skills/archer/swifttrap.cpp"
	"skills/archer/talkiebox.cpp"
	"skills/archer/verduretrap.cpp"
	"skills/archer/wargbite.cpp"
	"skills/archer/wargdash.cpp"
	"skills/archer/wargmastery.cpp"
	"skills/archer/wargrider.cpp"
	"skills/archer/wargstrike.cpp"
	"skills/archer/wildwalk.cpp"
	"skills/archer/windwalker.cpp"
	"skills/custom/skill_factory_custom.cpp"
	"skills/gunslinger/bullseye.cpp"
	"skills/gunslinger/cracker.cpp"
	"skills/gunslinger/desperado.cpp"
	"skills/gunslinger/disarm.cpp"
	"skills/gunslinger/dust.cpp"
	"skills/gunslinger/fling.cpp"
	"skills/gunslinger/fullbuster.cpp"
	"skills/gunslinger/gatlingfever.cpp"
	"skills/gunslinger/glittering.cpp"
	"skills/gunslinger/grounddrift.cpp"
	"skills/gunslinger/piercingshot.cpp"
	"skills/gunslinger/rapidshower.cpp"
	"skills/gunslinger/skill_factory_gunslinger.cpp"
	"skills/gunslinger/spreadattack.cpp"
	"skills/gunslinger/tracking.cpp"
	"skills/gunslinger/tripleaction.cpp"
	"skills/mage/allbloom.cpp"
	"skills/mage/astralstrike.cpp"
	"skills/mage/chainlightning.cpp"
	"skills/mage/coldbolt.cpp"
	"skills/mage/comet.cpp"
	"skills/mage/crimsonarrow.cpp"
	"skills/mage/crimsonrock.cpp"
	"skills/mage/crystalimpact.cpp"
	"skills/mage/deadlyprojection.cpp"
	"skills/mage/destructivehurricane.cpp"
	"skills/mage/drainlife.cpp"
	"skills/mage/earthspike.cpp"
	"skills/mage/earthstrain.cpp"
	"skills/mage/energycoat.cpp"
	"skills/mage/energyconversion.cpp"
	"skills/mage/fireball.cpp"
	"skills/mage/firebolt.cpp"
	"skills/mage/firepillar.cpp"
	"skills/mage/firewall.cpp"
	"skills/mage/floralflareroad.cpp"
	"skills/mage/frostdiver.cpp"
	"skills/mage/frostnova.cpp"
	"skills/mage/frostymisty.cpp"
	"skills/mage/frozenslash.cpp"
	"skills/mage/ganbantein.cpp"
	"skills/mage/gravitationfield.cpp"
	"skills/mage/heavensdrive.cpp"
	"skills/mage/hellinferno.cpp"
	"skills/mage/icewall.cpp"
	"skills/mage/jackfrost.cpp"
	"skills/mage/jupitelthunder.cpp"
	"skills/mage/lightningbolt.cpp"
	"skills/mage/lordofvermilion.cpp"
	"skills/mage/meteorstorm.cpp"
	"skills/mage/mysteryillusion.cpp"
	"skills/mage/napalmbeat.cpp"
	"skills/mage/napalmvulcan.cpp"
	"skills/mage/quagmire.cpp"
	"skills/mage/rainofcrystal.cpp"
	"skills/mage/readingspellbook.cpp"
	"skills/mage/release.cpp"
	"skills/mage/rockdown.cpp"
	"skills/mage/safetywall.cpp"
	"skills/mage/sense.cpp"
	"skills/mage/siennaexecrate.cpp"
	"skills/mage/sightblaster.cpp"
	"skills/mage/sight.cpp"
	"skills/mage/sightrasher.cpp"
	"skills/mage/skill_factory_mage.cpp"
	"skills/mage/soulexpansion.cpp"
	"skills/mage/soulstrike.cpp"
	"skills/mage/soulvulcanstrike.cpp"
	"skills/mage/stasis.cpp"
	"skills/mage/stonecurse.cpp"
	"skills/mage/stormcannon.cpp"
	"skills/mage/stormgust.cpp"
	"skills/mage/strantumtremor.cpp"
	"skills/mage/summonfireball.cpp"
	"skills/mage/summonlightningball.cpp"
	"skills/mage/summonstone.cpp"
	"skills/mage/summonwaterball.cpp"
	"skills/mage/tetravortex.cpp"
	"skills/mage/thunderstorm.cpp"
	"skills/mage/tornadostorm.cpp"
	"skills/mage/violentquake.cpp"
	"skills/mage/waterball.cpp"
	"skills/mage/whiteimprison.cpp"
	"skills/mercenary/mercenary_bash.cpp"
	"skills/mercenary/skill_factory_mercenary.cpp"
	"skills/merchant/abrbattlewarior.cpp"
	"skills/merchant/abrdualcannon.cpp"
	"skills/merchant/abrinfinity.cpp"
	"skills/merchant/abrmothernet.cpp"
	"skills/merchant/aciddemonstration.cpp"
	"skills/merchant/acidterror.cpp"
	"skills/merchant/adrenalinerush.cpp"
	"skills/merchant/advancedadrenalinerush.cpp"
	"skills/merchant/aidberserkpotion.cpp"
	"skills/merchant/aidcondensedpotion.cpp"
	"skills/merchant/aidpotion.cpp"
	"skills/merchant/alchemicalweapon.cpp"
	"skills/merchant/attackmachine.cpp"
	"skills/merchant/axestomp.cpp"
	"skills/merchant/biochemicalhelm.cpp"
	"skills/merchant/bomb.cpp"
	"skills/merchant/callhomunculus.cpp"
	"skills/merchant/cartrevolution.cpp"
	"skills/merchant/carttermination.cpp"
	"skills/merchant/changecart.cpp"
	"skills/merchant/crazyuproar.cpp"
	"skills/merchant/decoratecart.cpp"
	"skills/merchant/energycannonade.cpp"
	"skills/merchant/fullprotection.cpp"
	"skills/merchant/greed.cpp"
	"skills/merchant/hammerfall.cpp"
	"skills/merchant/itemappraisal.cpp"
	"skills/merchant/mammonite.cpp"
	"skills/merchant/manufacturemachine.cpp"
	"skills/merchant/mightysmash.cpp"
	"skills/merchant/plantcultivation.cpp"
	"skills/merchant/powerfulswing.cpp"
	"skills/merchant/powerthrust.cpp"
	"skills/merchant/preparepotion.cpp"
	"skills/merchant/rushquake.cpp"
	"skills/merchant/rushstrike.cpp"
	"skills/merchant/skill_factory_merchant.cpp"
	"skills/merchant/skill_vending.cpp"
	"skills/merchant/sparkblaster.cpp"
	"skills/merchant/summonflora.cpp"
	"skills/merchant/summonmarinesphere.cpp"
	"skills/merchant/synthesizedshield.cpp"
	"skills/merchant/syntheticarmor.cpp"
	"skills/merchant/triplelaser.cpp"
	"skills/merchant/twilightalchemy1.cpp"
	"skills/merchant/twilightalchemy2.cpp"
	"skills/merchant/twilightalchemy3.cpp"
	"skills/merchant/upgradeweapon.cpp"
	"skills/merchant/vaporize.cpp"
	"skills/merchant/weaponperfection.cpp"
	"skills/merchant/weaponrepair.cpp"
	"skills/ninja/skill_factory_ninja.cpp"
	"skills/novice/doublebowlingbash.cpp"
	"skills/novice/groundgravitation.cpp"
	"skills/novice/hellsdrive.cpp"
	"skills/novice/helpangel.cpp"
	"skills/novice/jackfrostnova.cpp"
	"skills/novice/jupitelthunderstorm.cpp"
	"skills/novice/megasonicblow.cpp"
	"skills/novice/meteorstormbuster.cpp"
	"skills/novice/napalmvulcanstrike.cpp"
	"skills/novice/overcomingcrisis.cpp"
	"skills/novice/shieldchainrush.cpp"
	"skills/novice/skill_factory_novice.cpp"
	"skills/novice/spiralpiercemax.cpp"
	"skills/npc/skill_factory_npc.cpp"
	"skills/summoner/skill_factory_summoner.cpp"
	"skills/swordman/autoberserk.cpp"
	"skills/swordman/bash.cpp"
	"skills/swordman/bowlingbash.cpp"
	"skills/swordman/brandishspear.cpp"
	"skills/swordman/counterattack.cpp"
	"skills/swordman/crossrain.cpp"
	"skills/swordman/dragonicaura.cpp"
	"skills/swordman/dragonicbreath.cpp"
	"skills/swordman/dragonicpierce.cpp"
	"skills/swordman/grandcross.cpp"
	"skills/swordman/grandjudgement.cpp"
	"skills/swordman/guardianshield.cpp"
	"skills/swordman/hackandslasher.cpp"
	"skills/swordman/holycross.cpp"
	"skills/swordman/imperialcross.cpp"
	"skills/swordman/imperialpressure.cpp"
	"skills/swordman/judgementcross.cpp"
	"skills/swordman/madnesscrusher.cpp"
	"skills/swordman/magnum.cpp"
	"skills/swordman/overslash.cpp"
	"skills/swordman/pierce.cpp"
	"skills/swordman/provoke.cpp"
	"skills/swordman/radiantspear.cpp"
	"skills/swordman/relax.cpp"
	"skills/swordman/resistantsouls.cpp"
	"skills/swordman/sacrifice.cpp"
	"skills/swordman/selfprovoke.cpp"
	"skills/swordman/servantweapon.cpp"
	"skills/swordman/servantweapondemolition.cpp"
	"skills/swordman/servantweaponphantom.cpp"
	"skills/swordman/servantweaponsign.cpp"
	"skills/swordman/shieldboomerang.cpp"
	"skills/swordman/shieldreflect.cpp"
	"skills/swordman/shieldshooting.cpp"
	"skills/swordman/skill_factory_swordman.cpp"
	"skills/swordman/smite.cpp"
	"skills/swordman/spearboomerang.cpp"
	"skills/swordman/spearstab.cpp"
	"skills/swordman/spiralpierce.cpp"
	"skills/swordman/stormslash.cpp"
	"skills/swordman/traumaticblow.cpp"
	"skills/swordman/ultimatesacrifice.cpp"
	"skills/swordman/vitalstrike.cpp"
	"skills/taekwon/circleofdirectionsandelementals.cpp"
	"skills/taekwon/counter.cpp"
	"skills/taekwon/downkick.cpp"
	"skills/taekwon/eska.cpp"
	"skills/taekwon/eske.cpp"
	"skills/taekwon/esma.cpp"
	"skills/taekwon/estin.cpp"
	"skills/taekwon/estun.cpp"
	"skills/taekwon/eswoo.cpp"
	"skills/taekwon/exorcismofmalicioussoul.cpp"
	"skills/taekwon/feelingthesunmoonandstars.cpp"
	"skills/taekwon/hatredofthesunmoonandstars.cpp"
	"skills/taekwon/highjump.cpp"
	"skills/taekwon/jumpkick.cpp"
	"skills/taekwon/kaahi.cpp"
	"skills/taekwon/kaite.cpp"
	"skills/taekwon/kaizel.cpp"
	"skills/taekwon/kaupe.cpp"
	"skills/taekwon/mission.cpp"
	"skills/taekwon/run.cpp"
	"skills/taekwon/sevenwind.cpp"
	"skills/taekwon/skill_factory_taekwon.cpp"
	"skills/taekwon/soulgathering.cpp"
	"skills/taekwon/soulofheavenandearth.cpp"
	"skills/taekwon/spiritofrebirth.cpp"
	"skills/taekwon/spiritofthealchemist.cpp"
	"skills/taekwon/spiritoftheartist.cpp"
	"skills/taekwon/spiritoftheassasin.cpp"
	"skills/taekwon/spiritoftheblacksmith.cpp"
	"skills/taekwon/spiritofthecrusader.cpp"
	"skills/taekwon/spiritofthehunter.cpp"
	"skills/taekwon/spiritoftheknight.cpp"
	"skills/taekwon/spiritofthemonk.cpp"
	"skills/taekwon/spiritofthepriest.cpp"
	"skills/taekwon/spiritoftherogue.cpp"
	"skills/taekwon/spiritofthesage.cpp"
	"skills/taekwon/spiritofthesoullinker.cpp"
	"skills/taekwon/spiritofthestargladiator.cpp"
	"skills/taekwon/spiritofthesupernovice.cpp"
	"skills/taekwon/spiritofthewizard.cpp"
	"skills/taekwon/stormkick.cpp"
	"skills/taekwon/talismanofblacktortoise.cpp"
	"skills/taekwon/talismanofbluedragon.cpp"
	"skills/taekwon/talismanoffiveelements.cpp"
	"skills/taekwon/talismanoffourbearinggod.cpp"
	"skills/taekwon/talismanofmagician.cpp"
	"skills/taekwon/talismanofprotection.cpp"
	"skills/taekwon/talismanofredphoenix.cpp"
	"skills/taekwon/talismanofsoulstealing.cpp"
	"skills/taekwon/talismanofwarrior.cpp"
	"skills/taekwon/talismanofwhitetiger.cpp"
	"skills/taekwon/totemoftutelary.cpp"
	"skills/taekwon/turnkick.cpp"
	"skills/taekwon/warmthofthemoon.cpp"
	"skills/taekwon/warmthofthestars.cpp"
	"skills/taekwon/warmthofthesun.cpp"
	"skills/thief/antidote.cpp"
	"skills/thief/backslide.cpp"
	"skills/thief/backstab.cpp"
	"skills/thief/cloaking.cpp"
	"skills/thief/cloakingexceed.cpp"
	"skills/thief/closeconfine.cpp"
	"skills/thief/counterinstinct.cpp"
	"skills/thief/counterslash.cpp"
	"skills/thief/createdeadlypoison.cpp"
	"skills/thief/createnewpoison.cpp"
	"skills/thief/crossimpact.cpp"
	"skills/thief/crossripperslasher.cpp"
	"skills/thief/crossslash.cpp"
	"skills/thief/dancingknife.cpp"
	"skills/thief/darkclaw.cpp"
	"skills/thief/darkillusion.cpp"
	"skills/thief/detoxify.cpp"
	"skills/thief/divestall.cpp"
	"skills/thief/divestarmor.cpp"
	"skills/thief/divesthelm.cpp"
	"skills/thief/divestshield.cpp"
	"skills/thief/divestweapon.cpp"
	"skills/thief/enchantdeadlypoison.cpp"
	"skills/thief/enchantpoison.cpp"
	"skills/thief/envenom.cpp"
	"skills/thief/eternalslash.cpp"
	"skills/thief/fatalshadowcrow.cpp"
	"skills/thief/findstone.cpp"
	"skills/thief/grimtooth.cpp"
	"skills/thief/hallucinationwalk.cpp"
	"skills/thief/hiding.cpp"
	"skills/thief/impactcrater.cpp"
	"skills/thief/meteorassault.cpp"
	"skills/thief/mug.cpp"
	"skills/thief/phantommenace.cpp"
	"skills/thief/poisoningweapon.cpp"
	"skills/thief/poisonsmoke.cpp"
	"skills/thief/remover.cpp"
	"skills/thief/rollingcutter.cpp"
	"skills/thief/sandattack.cpp"
	"skills/thief/savageimpact.cpp"
	"skills/thief/scribble.cpp"
	"skills/thief/shadowstab.cpp"
	"skills/thief/sightlessmind.cpp"
	"skills/thief/skill_factory_thief.cpp"
	"skills/thief/snatch.cpp"
	"skills/thief/sonicblow.cpp"
	"skills/thief/souldestroyer.cpp"
	"skills/thief/steal.cpp"
	"skills/thief/stealth.cpp"
	"skills/thief/stonefling.cpp"
	"skills/thief/throwvenomknife.cpp"
	"skills/thief/venomdust.cpp"
	"skills/thief/venompressure.cpp"
	"skills/thief/venomsplasher.cpp"
	"skills/thief/weaponcrush.cpp"
)

set(MAP_HEADERS
	"achievement.hpp"
	"atcommand.hpp"
	"battleground.hpp"
	"battle.hpp"
	"buyingstore.hpp"
	"cashshop.hpp"
	"channel.hpp"
	"chat.hpp"
	"chrif.hpp"
	"clan.hpp"
	"clif.hpp"
	"clif_obfuscation.hpp"
	"clif_packetdb.hpp"
	"clif_shuffle.hpp"
	"date.hpp"
	"duel.hpp"
	"elemental.hpp"
	"guild.hpp"
	"homunculus.hpp"
	"instance.hpp"
	"intif.hpp"
	"itemdb.hpp"
	"log.hpp"
	"mail.hpp"
	"map.hpp"
	"mapreg.hpp"
	"mercenary.hpp"
	"mob.hpp"
	"navi.hpp"
	"npc.hpp"
	"packets.hpp"
	"packets_struct.hpp"
	"party.hpp"
	"path.hpp"
	"pc_groups.hpp"
	"pc.hpp"
	"pet.hpp"
	"quest.hpp"
	"script_constants.hpp"
	"script.hpp"
	"searchstore.hpp"
	"skill.hpp"
	"status.hpp"
	"storage.hpp"
	"trade.hpp"
	"unit.hpp"
	"vending.hpp"

	"skills/skill_factory.hpp"
	"skills/skill_impl.hpp"
	"skills/weapon_skill_impl.hpp"
	"skills/status_skill_impl.hpp"

	"skills/acolyte/adoramus.hpp"
	"skills/acolyte/ancilla.hpp"
	"skills/acolyte/angelus.hpp"
	"skills/acolyte/arbitrium.hpp"
	"skills/acolyte/aspersio.hpp"
	"skills/acolyte/blazingflameblast.hpp"
	"skills/acolyte/blessing.hpp"
	"skills/acolyte/bssacramenti.hpp"
	"skills/acolyte/cantocandidus.hpp"
	"skills/acolyte/clearance.hpp"
	"skills/acolyte/coluceoheal.hpp"
	"skills/acolyte/competentia.hpp"
	"skills/acolyte/convenio.hpp"
	"skills/acolyte/crementia.hpp"
	"skills/acolyte/crucis.hpp"
	"skills/acolyte/cure.hpp"
	"skills/acolyte/decagi.hpp"
	"skills/acolyte/dilectioheal.hpp"
	"skills/acolyte/divinusflos.hpp"
	"skills/acolyte/duplelight.hpp"
	"skills/acolyte/effligo.hpp"
	"skills/acolyte/epiclesis.hpp"
	"skills/acolyte/explosionblaster.hpp"
	"skills/acolyte/firstbrand.hpp"
	"skills/acolyte/framen.hpp"
	"skills/acolyte/gloria.hpp"
	"skills/acolyte/heal.hpp"
	"skills/acolyte/highnessheal.hpp"
	"skills/acolyte/holylight.hpp"
	"skills/acolyte/holywater.hpp"
	"skills/acolyte/impositiomanus.hpp"
	"skills/acolyte/incagi.hpp"
	"skills/acolyte/judex.hpp"
	"skills/acolyte/kyrieeleison.hpp"
	"skills/acolyte/laudaagnus.hpp"
	"skills/acolyte/laudaramus.hpp"
	"skills/acolyte/lexdivina.hpp"
	"skills/acolyte/magnificat.hpp"
	"skills/acolyte/magnusexorcismus.hpp"
	"skills/acolyte/massiveflameblaster.hpp"
	"skills/acolyte/medialevotum.hpp"
	"skills/acolyte/oleumsanctum.hpp"
	"skills/acolyte/oratio.hpp"
	"skills/acolyte/petitio.hpp"
	"skills/acolyte/pneuma.hpp"
	"skills/acolyte/pneumaticusprocella.hpp"
	"skills/acolyte/praefatio.hpp"
	"skills/acolyte/renovatio.hpp"
	"skills/acolyte/reparatio.hpp"
	"skills/acolyte/ruwach.hpp"
	"skills/acolyte/sanctuary.hpp"
	"skills/acolyte/secondfaith.hpp"
	"skills/acolyte/secondflame.hpp"
	"skills/acolyte/secondjudgement.hpp"
	"skills/acolyte/silentium.hpp"
	"skills/acolyte/skill_factory_acolyte.hpp"
	"skills/acolyte/statusrecovery.hpp"
	"skills/acolyte/suffragium.hpp"
	"skills/acolyte/thirdconsecration.hpp"
	"skills/acolyte/thirdflamebomb.hpp"
	"skills/acolyte/thirdpunish.hpp"
	"skills/acolyte/turnundead.hpp"
	"skills/acolyte/vituperatum.hpp"
	"skills/archer/aimedbolt.hpp"
	"skills/archer/anklesnare.hpp"
	"skills/archer/arrowshower.hpp"
	"skills/archer/arrowstorm.hpp"
	"skills/archer/beaststrafing.hpp"
	"skills/archer/blastmine.hpp"
	"skills/archer/blitzbeat.hpp"
	"skills/archer/camouflage.hpp"
	"skills/archer/chargearrow.hpp"
	"skills/archer/claymoretrap.hpp"
	"skills/archer/clusterbomb.hpp"
	"skills/archer/cobalttrap.hpp"
	"skills/archer/concentration.hpp"
	"skills/archer/crescivebolt.hpp"
	"skills/archer/deepblindtrap.hpp"
	"skills/archer/detect.hpp"
	"skills/archer/detonator.hpp"
	"skills/archer/doublestrafe.hpp"
	"skills/archer/electricshocker.hpp"
	"skills/archer/falconassault.hpp"
	"skills/archer/fearbreeze.hpp"
	"skills/archer/firingtrap.hpp"
	"skills/archer/flametrap.hpp"
	"skills/archer/flasher.hpp"
	"skills/archer/focusedarrowstrike.hpp"
	"skills/archer/freezingtrap.hpp"
	"skills/archer/galestorm.hpp"
	"skills/archer/hawkboomerang.hpp"
	"skills/archer/hawkmastery.hpp"
	"skills/archer/hawkrush.hpp"
	"skills/archer/iceboundtrap.hpp"
	"skills/archer/landmine.hpp"
	"skills/archer/magentatrap.hpp"
	"skills/archer/maizetrap.hpp"
	"skills/archer/makingarrow.hpp"
	"skills/archer/phantasmicarrow.hpp"
	"skills/archer/removetrap.hpp"
	"skills/archer/sandman.hpp"
	"skills/archer/sensitivekeen.hpp"
	"skills/archer/shockwavetrap.hpp"
	"skills/archer/skidtrap.hpp"
	"skills/archer/skill_factory_archer.hpp"
	"skills/archer/solidtrap.hpp"
	"skills/archer/springtrap.hpp"
	"skills/archer/swifttrap.hpp"
	"skills/archer/talkiebox.hpp"
	"skills/archer/verduretrap.hpp"
	"skills/archer/wargbite.hpp"
	"skills/archer/wargdash.hpp"
	"skills/archer/wargmastery.hpp"
	"skills/archer/wargrider.hpp"
	"skills/archer/wargstrike.hpp"
	"skills/archer/wildwalk.hpp"
	"skills/archer/windwalker.hpp"
	"skills/custom/skill_factory_custom.hpp"
	"skills/gunslinger/bullseye.hpp"
	"skills/gunslinger/cracker.hpp"
	"skills/gunslinger/desperado.hpp"
	"skills/gunslinger/disarm.hpp"
	"skills/gunslinger/dust.hpp"
	"skills/gunslinger/fling.hpp"
	"skills/gunslinger/fullbuster.hpp"
	"skills/gunslinger/gatlingfever.hpp"
	"skills/gunslinger/glittering.hpp"
	"skills/gunslinger/grounddrift.hpp"
	"skills/gunslinger/piercingshot.hpp"
	"skills/gunslinger/rapidshower.hpp"
	"skills/gunslinger/skill_factory_gunslinger.hpp"
	"skills/gunslinger/spreadattack.hpp"
	"skills/gunslinger/tracking.hpp"
	"skills/gunslinger/tripleaction.hpp"
	"skills/mage/allbloom.hpp"
	"skills/mage/astralstrike.hpp"
	"skills/mage/chainlightning.hpp"
	"skills/mage/coldbolt.hpp"
	"skills/mage/comet.hpp"
	"skills/mage/crimsonarrow.hpp"
	"skills/mage/crimsonrock.hpp"
	"skills/mage/crystalimpact.hpp"
	"skills/mage/deadlyprojection.hpp"
	"skills/mage/destructivehurricane.hpp"
	"skills/mage/drainlife.hpp"
	"skills/mage/earthspike.hpp"
	"skills/mage/earthstrain.hpp"
	"skills/mage/energycoat.hpp"
	"skills/mage/energyconversion.hpp"
	"skills/mage/fireball.hpp"
	"skills/mage/firebolt.hpp"
	"skills/mage/firepillar.hpp"
	"skills/mage/firewall.hpp"
	"skills/mage/floralflareroad.hpp"
	"skills/mage/frostdiver.hpp"
	"skills/mage/frostnova.hpp"
	"skills/mage/frostymisty.hpp"
	"skills/mage/frozenslash.hpp"
	"skills/mage/ganbantein.hpp"
	"skills/mage/gravitationfield.hpp"
	"skills/mage/heavensdrive.hpp"
	"skills/mage/hellinferno.hpp"
	"skills/mage/icewall.hpp"
	"skills/mage/jackfrost.hpp"
	"skills/mage/jupitelthunder.hpp"
	"skills/mage/lightningbolt.hpp"
	"skills/mage/lordofvermilion.hpp"
	"skills/mage/meteorstorm.hpp"
	"skills/mage/mysteryillusion.hpp"
	"skills/mage/napalmbeat.hpp"
	"skills/mage/napalmvulcan.hpp"
	"skills/mage/quagmire.hpp"
	"skills/mage/rainofcrystal.hpp"
	"skills/mage/readingspellbook.hpp"
	"skills/mage/release.hpp"
	"skills/mage/rockdown.hpp"
	"skills/mage/safetywall.hpp"
	"skills/mage/sense.hpp"
	"skills/mage/siennaexecrate.hpp"
	"skills/mage/sightblaster.hpp"
	"skills/mage/sight.hpp"
	"skills/mage/sightrasher.hpp"
	"skills/mage/skill_factory_mage.hpp"
	"skills/mage/soulexpansion.hpp"
	"skills/mage/soulstrike.hpp"
	"skills/mage/soulvulcanstrike.hpp"
	"skills/mage/stasis.hpp"
	"skills/mage/stonecurse.hpp"
	"skills/mage/stormcannon.hpp"
	"skills/mage/stormgust.hpp"
	"skills/mage/strantumtremor.hpp"
	"skills/mage/summonfireball.hpp"
	"skills/mage/summonlightningball.hpp"
	"skills/mage/summonstone.hpp"
	"skills/mage/summonwaterball.hpp"
	"skills/mage/tetravortex.hpp"
	"skills/mage/thunderstorm.hpp"
	"skills/mage/tornadostorm.hpp"
	"skills/mage/violentquake.hpp"
	"skills/mage/waterball.hpp"
	"skills/mage/whiteimprison.hpp"
	"skills/mercenary/mercenary_bash.hpp"
	"skills/mercenary/skill_factory_mercenary.hpp"
	"skills/merchant/abrbattlewarior.hpp"
	"skills/merchant/abrdualcannon.hpp"
	"skills/merchant/abrinfinity.hpp"
	"skills/merchant/abrmothernet.hpp"
	"skills/merchant/aciddemonstration.hpp"
	"skills/merchant/acidterror.hpp"
	"skills/merchant/adrenalinerush.hpp"
	"skills/merchant/advancedadrenalinerush.hpp"
	"skills/merchant/aidberserkpotion.hpp"
	"skills/merchant/aidcondensedpotion.hpp"
	"skills/merchant/aidpotion.hpp"
	"skills/merchant/alchemicalweapon.hpp"
	"skills/merchant/attackmachine.hpp"
	"skills/merchant/axestomp.hpp"
	"skills/merchant/biochemicalhelm.hpp"
	"skills/merchant/bomb.hpp"
	"skills/merchant/callhomunculus.hpp"
	"skills/merchant/cartrevolution.hpp"
	"skills/merchant/carttermination.hpp"
	"skills/merchant/changecart.hpp"
	"skills/merchant/crazyuproar.hpp"
	"skills/merchant/decoratecart.hpp"
	"skills/merchant/energycannonade.hpp"
	"skills/merchant/fullprotection.hpp"
	"skills/merchant/greed.hpp"
	"skills/merchant/hammerfall.hpp"
	"skills/merchant/itemappraisal.hpp"
	"skills/merchant/mammonite.hpp"
	"skills/merchant/manufacturemachine.hpp"
	"skills/merchant/mightysmash.hpp"
	"skills/merchant/plantcultivation.hpp"
	"skills/merchant/powerfulswing.hpp"
	"skills/merchant/powerthrust.hpp"
	"skills/merchant/preparepotion.hpp"
	"skills/merchant/rushquake.hpp"
	"skills/merchant/rushstrike.hpp"
	"skills/merchant/skill_factory_merchant.hpp"
	"skills/merchant/skill_vending.hpp"
	"skills/merchant/sparkblaster.hpp"
	"skills/merchant/summonflora.hpp"
	"skills/merchant/summonmarinesphere.hpp"
	"skills/merchant/synthesizedshield.hpp"
	"skills/merchant/syntheticarmor.hpp"
	"skills/merchant/triplelaser.hpp"
	"skills/merchant/twilightalchemy1.hpp"
	"skills/merchant/twilightalchemy2.hpp"
	"skills/merchant/twilightalchemy3.hpp"
	"skills/merchant/upgradeweapon.hpp"
	"skills/merchant/vaporize.hpp"
	"skills/merchant/weaponperfection.hpp"
	"skills/merchant/weaponrepair.hpp"
	"skills/ninja/skill_factory_ninja.hpp"
	"skills/novice/doublebowlingbash.hpp"
	"skills/novice/groundgravitation.hpp"
	"skills/novice/hellsdrive.hpp"
	"skills/novice/helpangel.hpp"
	"skills/novice/jackfrostnova.hpp"
	"skills/novice/jupitelthunderstorm.hpp"
	"skills/novice/megasonicblow.hpp"
	"skills/novice/meteorstormbuster.hpp"
	"skills/novice/napalmvulcanstrike.hpp"
	"skills/novice/overcomingcrisis.hpp"
	"skills/novice/shieldchainrush.hpp"
	"skills/novice/skill_factory_novice.hpp"
	"skills/novice/spiralpiercemax.hpp"
	"skills/npc/skill_factory_npc.hpp"
	"skills/summoner/skill_factory_summoner.hpp"
	"skills/swordman/autoberserk.hpp"
	"skills/swordman/bash.hpp"
	"skills/swordman/bowlingbash.hpp"
	"skills/swordman/brandishspear.hpp"
	"skills/swordman/counterattack.hpp"
	"skills/swordman/crossrain.hpp"
	"skills/swordman/dragonicaura.hpp"
	"skills/swordman/dragonicbreath.hpp"
	"skills/swordman/dragonicpierce.hpp"
	"skills/swordman/grandcross.hpp"
	"skills/swordman/grandjudgement.hpp"
	"skills/swordman/guardianshield.hpp"
	"skills/swordman/hackandslasher.hpp"
	"skills/swordman/holycross.hpp"
	"skills/swordman/imperialcross.hpp"
	"skills/swordman/imperialpressure.hpp"
	"skills/swordman/judgementcross.hpp"
	"skills/swordman/madnesscrusher.hpp"
	"skills/swordman/magnum.hpp"
	"skills/swordman/overslash.hpp"
	"skills/swordman/pierce.hpp"
	"skills/swordman/provoke.hpp"
	"skills/swordman/radiantspear.hpp"
	"skills/swordman/relax.hpp"
	"skills/swordman/resistantsouls.hpp"
	"skills/swordman/sacrifice.hpp"
	"skills/swordman/selfprovoke.hpp"
	"skills/swordman/servantweapondemolition.hpp"
	"skills/swordman/servantweapon.hpp"
	"skills/swordman/servantweaponphantom.hpp"
	"skills/swordman/servantweaponsign.hpp"
	"skills/swordman/shieldboomerang.hpp"
	"skills/swordman/shieldreflect.hpp"
	"skills/swordman/shieldshooting.hpp"
	"skills/swordman/skill_factory_swordman.hpp"
	"skills/swordman/smite.hpp"
	"skills/swordman/spearboomerang.hpp"
	"skills/swordman/spearstab.hpp"
	"skills/swordman/spiralpierce.hpp"
	"skills/swordman/stormslash.hpp"
	"skills/swordman/traumaticblow.hpp"
	"skills/swordman/ultimatesacrifice.hpp"
	"skills/swordman/vitalstrike.hpp"
	"skills/taekwon/circleofdirectionsandelementals.hpp"
	"skills/taekwon/counter.hpp"
	"skills/taekwon/downkick.hpp"
	"skills/taekwon/eska.hpp"
	"skills/taekwon/eske.hpp"
	"skills/taekwon/esma.hpp"
	"skills/taekwon/estin.hpp"
	"skills/taekwon/estun.hpp"
	"skills/taekwon/eswoo.hpp"
	"skills/taekwon/exorcismofmalicioussoul.hpp"
	"skills/taekwon/feelingthesunmoonandstars.hpp"
	"skills/taekwon/hatredofthesunmoonandstars.hpp"
	"skills/taekwon/highjump.hpp"
	"skills/taekwon/jumpkick.hpp"
	"skills/taekwon/kaahi.hpp"
	"skills/taekwon/kaite.hpp"
	"skills/taekwon/kaizel.hpp"
	"skills/taekwon/kaupe.hpp"
	"skills/taekwon/mission.hpp"
	"skills/taekwon/run.hpp"
	"skills/taekwon/sevenwind.hpp"
	"skills/taekwon/skill_factory_taekwon.hpp"
	"skills/taekwon/soulgathering.hpp"
	"skills/taekwon/soulofheavenandearth.hpp"
	"skills/taekwon/spiritofrebirth.hpp"
	"skills/taekwon/spiritofthealchemist.hpp"
	"skills/taekwon/spiritoftheartist.hpp"
	"skills/taekwon/spiritoftheassasin.hpp"
	"skills/taekwon/spiritoftheblacksmith.hpp"
	"skills/taekwon/spiritofthecrusader.hpp"
	"skills/taekwon/spiritofthehunter.hpp"
	"skills/taekwon/spiritoftheknight.hpp"
	"skills/taekwon/spiritofthemonk.hpp"
	"skills/taekwon/spiritofthepriest.hpp"
	"skills/taekwon/spiritoftherogue.hpp"
	"skills/taekwon/spiritofthesage.hpp"
	"skills/taekwon/spiritofthesoullinker.hpp"
	"skills/taekwon/spiritofthestargladiator.hpp"
	"skills/taekwon/spiritofthesupernovice.hpp"
	"skills/taekwon/spiritofthewizard.hpp"
	"skills/taekwon/stormkick.hpp"
	"skills/taekwon/talismanofblacktortoise.hpp"
	"skills/taekwon/talismanofbluedragon.hpp"
	"skills/taekwon/talismanoffiveelements.hpp"
	"skills/taekwon/talismanoffourbearinggod.hpp"
	"skills/taekwon/talismanofmagician.hpp"
	"skills/taekwon/talismanofprotection.hpp"
	"skills/taekwon/talismanofredphoenix.hpp"
	"skills/taekwon/talismanofsoulstealing.hpp"
	"skills/taekwon/talismanofwarrior.hpp"
	"skills/taekwon/talismanofwhitetiger.hpp"
	"skills/taekwon/totemoftutelary.hpp"
	"skills/taekwon/turnkick.hpp"
	"skills/taekwon/warmthofthemoon.hpp"
	"skills/taekwon/warmthofthestars.hpp"
	"skills/taekwon/warmthofthesun.hpp"
	"skills/thief/antidote.hpp"
	"skills/thief/backslide.hpp"
	"skills/thief/backstab.hpp"
	"skills/thief/cloakingexceed.hpp"
	"skills/thief/cloaking.hpp"
	"skills/thief/closeconfine.hpp"
	"skills/thief/counterinstinct.hpp"
	"skills/thief/counterslash.hpp"
	"skills/thief/createdeadlypoison.hpp"
	"skills/thief/createnewpoison.hpp"
	"skills/thief/crossimpact.hpp"
	"skills/thief/crossripperslasher.hpp"
	"skills/thief/crossslash.hpp"
	"skills/thief/dancingknife.hpp"
	"skills/thief/darkclaw.hpp"
	"skills/thief/darkillusion.hpp"
	"skills/thief/detoxify.hpp"
	"skills/thief/divestall.hpp"
	"skills/thief/divestarmor.hpp"
	"skills/thief/divesthelm.hpp"
	"skills/thief/divestshield.hpp"
	"skills/thief/divestweapon.hpp"
	"skills/thief/enchantdeadlypoison.hpp"
	"skills/thief/enchantpoison.hpp"
	"skills/thief/envenom.hpp"
	"skills/thief/eternalslash.hpp"
	"skills/thief/fatalshadowcrow.hpp"
	"skills/thief/findstone.hpp"
	"skills/thief/grimtooth.hpp"
	"skills/thief/hallucinationwalk.hpp"
	"skills/thief/hiding.hpp"
	"skills/thief/impactcrater.hpp"
	"skills/thief/meteorassault.hpp"
	"skills/thief/mug.hpp"
	"skills/thief/phantommenace.hpp"
	"skills/thief/poisoningweapon.hpp"
	"skills/thief/poisonsmoke.hpp"
	"skills/thief/remover.hpp"
	"skills/thief/rollingcutter.hpp"
	"skills/thief/sandattack.hpp"
	"skills/thief/savageimpact.hpp"
	"skills/thief/scribble.hpp"
	"skills/thief/shadowstab.hpp"
	"skills/thief/sightlessmind.hpp"
	"skills/thief/skill_factory_thief.hpp"
	"skills/thief/snatch.hpp"
	"skills/thief/sonicblow.hpp"
	"skills/thief/souldestroyer.hpp"
	"skills/thief/steal.hpp"
	"skills/thief/stealth.hpp"
	"skills/thief/stonefling.hpp"
	"skills/thief/throwvenomknife.hpp"
	"skills/thief/venomdust.hpp"
	"skills/thief/venompressure.hpp"
	"skills/thief/venomsplasher.hpp"
	"skills/thief/weaponcrush.hpp"

)

add_library(map)

target_sources(map PRIVATE ${MAP_SOURCES})

if(WIN32)
	target_sources(map PRIVATE ${MAP_HEADERS})
	set_target_properties(map PROPERTIES FOLDER "Servers")
endif()

target_link_libraries(map PUBLIC
	common
	${PCRE_LIBRARIES}
)

target_include_directories(map PUBLIC
	${PCRE_INCLUDE_DIRS}
)

if(WITH_PCRE)
	target_compile_definitions(map PUBLIC "PCRE_SUPPORT")
endif()

add_executable(map-server "MapServerMain.cpp")
target_link_libraries(map-server PRIVATE map)

# map-server-generator
add_library(map-server-generator)

target_sources(map-server-generator PRIVATE ${MAP_SOURCES} "MapServerGeneratorMain.cpp")

if(WIN32)
	target_sources(map-server-generator PRIVATE ${MAP_HEADERS})
	set_target_properties(map-server-generator PROPERTIES FOLDER "Tools")
endif()

target_compile_definitions(map-server-generator PUBLIC "MAP_GENERATOR")

target_link_libraries(map-server-generator PUBLIC
	common
	json
	${PCRE_LIBRARIES}
)

target_include_directories(map-server-generator PUBLIC
	${PCRE_INCLUDE_DIRS}
)

if(WITH_PCRE)
	target_compile_definitions(map-server-generator PUBLIC "PCRE_SUPPORT")
endif()
