// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#include "skill_factory_swordman.hpp"

#include "../skill_impl.hpp"

#include "abundance.hpp"
#include "autoberserk.hpp"
#include "banding.hpp"
#include "banishingpoint.hpp"
#include "bash.hpp"
#include "battlechant.hpp"
#include "bowlingbash.hpp"
#include "brandishspear.hpp"
#include "cannonspear.hpp"
#include "counterattack.hpp"
#include "crossrain.hpp"
#include "crushstrike.hpp"
#include "dragonbreath.hpp"
#include "dragonhowling.hpp"
#include "dragonicaura.hpp"
#include "dragonicbreath.hpp"
#include "dragonicpierce.hpp"
#include "earthdrive.hpp"
#include "enchantblade.hpp"
#include "fightingspirit.hpp"
#include "forceofvanguard.hpp"
#include "giantgrowth.hpp"
#include "gloriadomini.hpp"
#include "grandcross.hpp"
#include "grandjudgement.hpp"
#include "guardianshield.hpp"
#include "hackandslasher.hpp"
#include "hesperuslit.hpp"
#include "holycross.hpp"
#include "hundredspear.hpp"
#include "ignitionbreak.hpp"
#include "imperialcross.hpp"
#include "imperialpressure.hpp"
#include "judgementcross.hpp"
#include "kingsgrace.hpp"
#include "luxanima.hpp"
#include "madnesscrusher.hpp"
#include "magnum.hpp"
#include "martyrsreckoning.hpp"
#include "milleniumshield.hpp"
#include "moonslasher.hpp"
#include "overbrand.hpp"
#include "overslash.hpp"
#include "phantomthrust.hpp"
#include "pierce.hpp"
#include "piety.hpp"
#include "pinpointattack.hpp"
#include "provoke.hpp"
#include "radiantspear.hpp"
#include "rageburst.hpp"
#include "rayofgenesis.hpp"
#include "refresh.hpp"
#include "relax.hpp"
#include "resistantsouls.hpp"
#include "sacrifice.hpp"
#include "selfprovoke.hpp"
#include "servantweapon.hpp"
#include "servantweapondemolition.hpp"
#include "servantweaponphantom.hpp"
#include "servantweaponsign.hpp"
#include "shieldboomerang.hpp"
#include "shieldchain.hpp"
#include "shieldpress.hpp"
#include "shieldreflect.hpp"
#include "shieldshooting.hpp"
#include "shieldspell.hpp"
#include "smite.hpp"
#include "sonicwave.hpp"
#include "spearboomerang.hpp"
#include "spearstab.hpp"
#include "spiralpierce.hpp"
#include "stonehardskin.hpp"
#include "stormblast.hpp"
#include "stormslash.hpp"
#include "trample.hpp"
#include "traumaticblow.hpp"
#include "ultimatesacrifice.hpp"
#include "vitalityactivation.hpp"
#include "vitalstrike.hpp"
#include "windcutter.hpp"

std::unique_ptr<const SkillImpl> SkillFactorySwordman::create(const e_skill skill_id) const {
	switch( skill_id ){
		case CR_AUTOGUARD:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case CR_DEFENDER:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case CR_DEVOTION:
			return std::make_unique<SkillSacrifice>();
		case CR_GRANDCROSS:
			return std::make_unique<SkillGrandCross>();
		case CR_HOLYCROSS:
			return std::make_unique<SkillHolyCross>();
		case CR_PROVIDENCE:
			return std::make_unique<SkillResistantSouls>();
		case CR_REFLECTSHIELD:
			return std::make_unique<SkillShieldReflect>();
		case CR_SHIELDBOOMERANG:
			return std::make_unique<SkillShieldBoomerang>();
		case CR_SHIELDCHARGE:
			return std::make_unique<SkillSmite>();
		case CR_SHRINK:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case CR_SPEARQUICKEN:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case DK_CHARGINGPIERCE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case DK_DRAGONIC_AURA:
			return std::make_unique<SkillDragonicAura>();
		case DK_DRAGONIC_BREATH:
			return std::make_unique<SkillDragonicBreath>();
		case DK_DRAGONIC_PIERCE:
			return std::make_unique<SkillDragonicPierce>();
		case DK_HACKANDSLASHER:
			return std::make_unique<SkillHackAndSlasher>();
		case DK_HACKANDSLASHER_ATK:
			return std::make_unique<SkillHackAndSlasherAttack>();
		case DK_MADNESS_CRUSHER:
			return std::make_unique<SkillMadnessCrusher>();
		case DK_SERVANTWEAPON:
			return std::make_unique<SkillServantWeapon>();
		case DK_SERVANTWEAPON_ATK:
			return std::make_unique<SkillServantWeaponAttack>();
		case DK_SERVANT_W_DEMOL:
			return std::make_unique<SkillServantWeaponDemolition>();
		case DK_SERVANT_W_PHANTOM:
			return std::make_unique<SkillServantWeaponPhantom>();
		case DK_SERVANT_W_SIGN:
			return std::make_unique<SkillServantWeaponSign>();
		case DK_STORMSLASH:
			return std::make_unique<SkillStormSlash>();
		case DK_VIGOR:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case IG_ATTACK_STANCE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case IG_CROSS_RAIN:
			return std::make_unique<SkillCrossRain>();
		case IG_GRAND_JUDGEMENT:
			return std::make_unique<SkillGrandJudgement>();
		case IG_GUARD_STANCE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case IG_GUARDIAN_SHIELD:
			return std::make_unique<SkillGuardianShield>();
		case IG_HOLY_SHIELD:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case IG_IMPERIAL_CROSS:
			return std::make_unique<SkillImperialCross>();
		case IG_IMPERIAL_PRESSURE:
			return std::make_unique<SkillImperialPressure>();
		case IG_JUDGEMENT_CROSS:
			return std::make_unique<SkillJudgementCross>();
		case IG_OVERSLASH:
			return std::make_unique<SkillOverSlash>();
		case IG_RADIANT_SPEAR:
			return std::make_unique<SkillRadiantSpear>();
		case IG_REBOUND_SHIELD:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case IG_SHIELD_SHOOTING:
			return std::make_unique<SkillShieldShooting>();
		case IG_ULTIMATE_SACRIFICE:
			return std::make_unique<SkillUltimateSacrifice>();
		case KN_AUTOCOUNTER:
			return std::make_unique<SkillCounterAttack>();
		case KN_BOWLINGBASH:
			return std::make_unique<SkillBowlingBash>();
		case KN_BRANDISHSPEAR:
			return std::make_unique<SkillBrandishSpear>();
		case KN_ONEHAND:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case KN_PIERCE:
			return std::make_unique<SkillPierce>();
		case KN_SPEARBOOMERANG:
			return std::make_unique<SkillSpearBoomerang>();
		case KN_SPEARSTAB:
			return std::make_unique<SkillSpearStab>();
		case KN_TWOHANDQUICKEN:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LG_BANDING:
			return std::make_unique<SkillBanding>();
		case LG_BANISHINGPOINT:
			return std::make_unique<SkillBanishingPoint>();
		case LG_CANNONSPEAR:
			return std::make_unique<SkillCannonSpear>();
		case LG_EARTHDRIVE:
			return std::make_unique<SkillEarthDrive>();
		case LG_EXEEDBREAK:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LG_FORCEOFVANGUARD:
			return std::make_unique<SkillForceOfVanguard>();
		case LG_HESPERUSLIT:
			return std::make_unique<SkillHesperusLit>();
		case LG_INSPIRATION:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LG_KINGS_GRACE:
			return std::make_unique<SkillKingsGrace>();
		case LG_MOONSLASHER:
			return std::make_unique<SkillMoonSlasher>();
		case LG_OVERBRAND:
			return std::make_unique<SkillOverBrand>();
		case LG_PIETY:
			return std::make_unique<SkillPiety>();
		case LG_PINPOINTATTACK:
			return std::make_unique<SkillPinpointAttack>();
		case LG_PRESTIGE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LG_RAGEBURST:
			return std::make_unique<SkillRageBurst>();
		case LG_RAYOFGENESIS:
			return std::make_unique<SkillRayOfGenesis>();
		case LG_REFLECTDAMAGE:
			return std::make_unique<StatusSkillImpl>(skill_id, true);
		case LG_SHIELDPRESS:
			return std::make_unique<SkillShieldPress>();
		case LG_SHIELDSPELL:
			return std::make_unique<SkillShieldSpell>();
		case LG_TRAMPLE:
			return std::make_unique<SkillTrample>();
		case LK_AURABLADE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LK_BERSERK:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LK_CONCENTRATION:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LK_HEADCRUSH:
			return std::make_unique<SkillTraumaticBlow>();
		case LK_JOINTBEAT:
			return std::make_unique<SkillVitalStrike>();
		case LK_PARRYING:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case LK_SPIRALPIERCE:
			return std::make_unique<SkillSpiralPierce>();
		case LK_TENSIONRELAX:
			return std::make_unique<SkillRelax>();
		case PA_GOSPEL:
			return std::make_unique<SkillBattleChant>();
		case PA_PRESSURE:
			return std::make_unique<SkillGloriaDomini>();
		case PA_SACRIFICE:
			return std::make_unique<SkillMartyrsReckoning>();
		case PA_SHIELDCHAIN:
			return std::make_unique<SkillShieldChain>();
		case RK_ABUNDANCE:
			return std::make_unique<SkillAbundance>();
		case RK_CRUSHSTRIKE:
			return std::make_unique<SkillCrushStrike>();
		case RK_DEATHBOUND:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case RK_DRAGONBREATH:
			return std::make_unique<SkillDragonBreath>();
		case RK_DRAGONBREATH_WATER:
			return std::make_unique<SkillDragonBreathWater>();
		case RK_DRAGONHOWLING:
			return std::make_unique<SkillDragonHowling>();
		case RK_ENCHANTBLADE:
			return std::make_unique<SkillEnchantBlade>();
		case RK_FIGHTINGSPIRIT:
			return std::make_unique<SkillFightingSpirit>();
		case RK_GIANTGROWTH:
			return std::make_unique<SkillGiantGrowth>();
		case RK_HUNDREDSPEAR:
			return std::make_unique<SkillHundredSpear>();
		case RK_IGNITIONBREAK:
			return std::make_unique<SkillIgnitionBreak>();
		case RK_LUXANIMA:
			return std::make_unique<SkillLuxAnima>();
		case RK_MILLENNIUMSHIELD:
			return std::make_unique<SkillMilleniumShield>();
		case RK_PHANTOMTHRUST:
			return std::make_unique<SkillPhantomThrust>();
		case RK_REFRESH:
			return std::make_unique<SkillRefresh>();
		case RK_SONICWAVE:
			return std::make_unique<SkillSonicWave>();
		case RK_STONEHARDSKIN:
			return std::make_unique<SkillStoneHardSkin>();
		case RK_STORMBLAST:
			return std::make_unique<SkillStormBlast>();
		case RK_VITALITYACTIVATION:
			return std::make_unique<SkillVitalityActivation>();
		case RK_WINDCUTTER:
			return std::make_unique<SkillWindCutter>();
		case SM_AUTOBERSERK:
			return std::make_unique<SkillAutoBerserk>();
		case SM_BASH:
			return std::make_unique<SkillBash>();
		case SM_ENDURE:
			return std::make_unique<StatusSkillImpl>(skill_id);
		case SM_MAGNUM:
			return std::make_unique<SkillMagnumBreak>();
		case SM_PROVOKE:
			return std::make_unique<SkillProvoke>();
		case SM_SELFPROVOKE:
			return std::make_unique<SkillProvokeSelf>();

		default:
			return nullptr;
	}
}
